GET http://localhost:3009/players

###
POST http://localhost:3009/players/
Content-Type: application/json

{
    "playerName":"Vishal",
    "jersyNumber":17,
    "role":"Bowler"
}

###

GET http://localhost:3009/players/1/

###

PUT http://localhost:3009/players/3/
Content-Type: application/json

###

DELETE http://localhost:3009/players/2/